### ISSUE TITLE
AddWatcher Function in Issue-Repository is not working

### ISSUE THREAD

**Issue by MarcoGiesen** [DanielBadura/Redmine-Api-Client#14]
The function addWatcher in the Issue-Repository is currently not working. The reason for this bug is a wrong GET url "/user/id.json", it should be "/users/id.json". The same applies for the deleteWatcher function as well.
I think two solutions are available:
1. Change user to users
2. Use the User-Repository, instead of duplicating the code

**Comment by DanielBadura** [comment]
Yes, that is right.
In the code of the IssueRepo is a comment that later on it should use the UserRepo. At this time the UserRepo didnt exist.

I'll edit this.

**Comment by DavidBadura** [comment]
you don't need `addWatcher` and `removeWatcher` in IssueRepository. You can add a watcher by editing or creating an issue.

> watcher_user_ids - Array of user ids to add as watchers (since 2.3.0)

This way is much better:

``` php
$issue = $client->getIssueRepository()->find(1);
$issue->addWatcher($user);
$client->getIssueRepository()->save($issue);
```

**Comment by DanielBadura** [comment]
The watcher is for an issue not for an user.
It is in the IssueRepository it just uses tje userRepo to check the user
exists.

**Comment by DavidBadura** [comment]
oh sorry, i have edited my post :wink:

**Comment by DanielBadura** [comment]
Yes that is true but this wasnt topic of this Issue.  But we will change it later on
